### ISSUE TITLE
rapidxml.hpp -W-sign-compare 

### ISSUE THREAD

**Issue by phansen01** [Cheedoong/xml2json#10]
in  
```c++
 void xmlns_lookup(Ch *& xmlns, size_t &xmlns_size, Ch * prefix, size_t prefix_size) const
```
```c++ 
//......
//......
//......
freeme = attrname = new Ch[prefix_size + 7];
const char * p1="xmlns";
while (*p1) *attrname++ = *p1++;
Ch * p = prefix;
*attrname++ = Ch(':');
while (*p) {
    *attrname++ = *p++;
    if ((attrname - freeme) >= (prefix_size + 6)) break;
}
```
the culprit line is 
```c++    
if ((attrname - freeme) >= (prefix_size + 6)) break; 
```

This can of course be ignored with compiler flags but in projects/environments where compiler flags can't be changed this won't work. 

casting `(prefix_size + 6)` also fixes but is probably not ideal (or if this is not true feel free to close).

**Comment by Cheedoong** [comment]
@phansen01  You are quite correct! I commented this line. 

To figure out whether compiler optimization flag makes a difference, I tried gcc with -O0 and -Os: 

![xml_-o0](https://cloud.githubusercontent.com/assets/4876415/14519226/189eba18-0250-11e6-866a-67b2df76a543.jpg)

![xml_-os](https://cloud.githubusercontent.com/assets/4876415/14519300/86d04bd2-0250-11e6-832b-153b79ba539b.jpg)

**Comment by Cheedoong** [comment]
By the way, the latest version supports `Mac OS X` now. 
@phansen01  @ztdwu 
Thanks @ZupIT (ZUP IT Innovation) from Brazil!

**Comment by phansen01** [comment]
Thanks, I'll close the issue now then.
