### ISSUE TITLE
Small issue with empty control statement

### ISSUE THREAD

**Issue by sturmf** [Cheedoong/xml2json#11]
In rapidxml.hpp there is a small issue with a control statement.
In line 516 you have:

            if (!m_nullstr);
                m_nullstr = allocate_string("");
            return m_nullstr;

As you can see there is a semicolon after the if statement. The consequence is that the m_nullstr is allocated every time it passes this sequence.

**Comment by Cheedoong** [comment]
@sturmf  fixed with thanks!
