### ISSUE TITLE
Request: parsing xml namespaces 

### ISSUE THREAD

**Issue by phansen01** [Cheedoong/xml2json#12]
When a tag like `<ns:element type="abc" />` is parsed, the `ns:` is ignored in conversion.

this isn't a huge deal in my use case, but it might be worth looking at.

**Comment by Cheedoong** [comment]
I made a special version for you. 
[xml2json.tar.gz](https://github.com/Cheedoong/xml2json/files/304456/xml2json.tar.gz)

Check the attached file and hope it handles the namespace problems well. 
See `test_track_1.xml` and `test_track_1.js.txt` in `/test/`. 

Reference; 
https://github.com/svgpp/rapidxml_ns

Cheers~

**Comment by phansen01** [comment]
Thanks a ton, I'll give this a shot.
