### ISSUE TITLE
Is a single child an object or an Array[1] of object?

### ISSUE THREAD

**Issue by jbmonroe** [Cheedoong/xml2json#15]
Given

```
<sale>
  <item>
    <plu>000001</plu>
    <price>75</price>
  </item>
</sale>
```
one gets
```
{
  "sale" : {
    "item" : {
      "plu" : "000001",
      "price" : 75;
   }
  }
}
```

but with
```
<sale>
  <item>
    <plu>000001</plu>
    <price>75</price>
  </item>
  <item>
    <plu>000006</plu>
    <price>3495</price>
  </item>
</sale>
```
one gets
```
{
  "sale" : {
    "item" : [
      {
        "plu" : "000001",
        "price" : 75;
      },
      {
        "plu" : "000006",
        "price" : 3495;
      }
    ]
}
```
Both are correct, but not equivalent when doing look-ups.  What's the best way to resolve the paradox?  Fork this on our own and then force Array[1] when there's a single node, or try to look ahead to determine how many child nodes have the same name?

**Comment by javadev** [comment]
@jbmonroe I found solution.

```json
{
   "sale": {
      "item": [
         {
            "plu": "000001",
            "price": "75"
         }
      ]
   }
}
```

will be cnverted to
```xml
<?xml version="1.0" encoding="UTF-8"?>
<sale>
  <item array="true">
    <plu>000001</plu>
    <price>75</price>
  </item>
</sale>
```

**Comment by jbmonroe** [comment]
Interesting, if slightly unexpected.  (That is, the WSDL would have to point it out so consumers would know the attribute was there.)  We delivered the solution to the customer last month, but I'll download any new version and incorporate it in the future.
