### ISSUE TITLE
Crash when parsing RSS xml    解析RSS会出错

### ISSUE THREAD

**Issue by scaucy** [Cheedoong/xml2json#8]
http://rss.golem.de/rss.php?feed=RSS1.0
http://www.heise.de/newsticker/heise-atom.xml
http://www.tagesschau.de/xml/rss2

Those RSS sources above will cause my program crash, console output: 
terminate called after throwing an instance of 'rapidxml::parse_error'
  what():  unexpected end of data

Maybe upstream project rapidxml does not support RSS xml.

上面的RSS源或导致程序崩溃，命令行输出：
terminate called after throwing an instance of 'rapidxml::parse_error'
  what():  unexpected end of data
也许可能是上游项目rapidxml对RSS支持不好

**Comment by Cheedoong** [comment]
@scaucy  上一次提交未充分检查，有些问题。
你再看看能否work？

**Comment by scaucy** [comment]
自己打脸。。。。。发现是我自己的问题导致。。。。。。。还是低级错误 (┙>∧<)┙へ┻┻
