### ISSUE TITLE
Broken after 7th January commit

### ISSUE THREAD

**Issue by fracasula** [Cheedoong/xml2json#9]
Hi there,

First of all thanks for your code, it's been very useful to me.
I noticed that it's not working on my side anymore since the commit you made on the 7th of January:

Here's my test:

    echo '<?xml version="1.0" encoding="UTF-8"?><hello>ciao</hello>' | xml2json

Output:

    {"hello":{}}

While it should be:

    {"hello":"ciao"}

If I pull [this version](https://github.com/Cheedoong/xml2json/tree/46968bcde6fbe570dae1cf9c33edddfb7b70f831) then it works.

**Comment by Cheedoong** [comment]
@fracasula  Sorry for the trouble caused by my carelessness. Hope, it's already been fixed. 
Check :)

**Comment by fracasula** [comment]
@Cheedoong cool, it works now! Thanks :smile:
